/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ChristyHsu (https://sketchfab.com/ida61xq)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cozy-living-room-baked-581238dc5fda4dc990571cdc02827783
title: Cozy living room baked
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame, useThree} from "@react-three/fiber";
import { gsap, Power2 } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger'
export function Model(props) {
    const { nodes, materials } = useGLTF('/models/dining/scene.glb');

    const ref = useRef();

    return (
        <group {...props} dispose={null} ref={ref}>
            <group rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.17}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <group position={[0, -4.89, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[1379.1, 1734, 765]}>
                        <mesh geometry={nodes.Modern_Dining_Room_Floor_0.geometry} material={materials.Floor} />
                        <mesh geometry={nodes.Walls_Walls_0.geometry} material={materials.Walls} position={[0, 0, 0.01]} scale={[0.99, 1, 1]} />
                        <mesh geometry={nodes.Roof_Roof_0.geometry} material={materials.Roof} position={[0, 0, 1.11]} scale={[0.99, 1, 1]} />
                        <mesh geometry={nodes.Backdrop_Backdrop_0.geometry} material={materials.Backdrop} position={[0, 1.56, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={[1.94, 3.5, 1.55]} />
                        <mesh geometry={nodes.DoorFrame_DoorFrame_0.geometry} material={materials.DoorFrame} position={[0, 1.13, -0.31]} scale={[0.99, 1, 1]} />
                        <mesh geometry={nodes.Window_Window_0.geometry} material={materials.Window} position={[0, 0, 0.01]} scale={[0.99, 1, 1]} />
                        <mesh geometry={nodes.DiningTable_DiningTable_0.geometry} material={materials.DiningTable} position={[0, 0.06, -0.57]} scale={[0.15, 0.12, 0.26]} />
                        <mesh geometry={nodes.Pot_Pot_0.geometry} material={materials.material} position={[0, 0.06, -0.43]} scale={[0.07, 0.06, 0.13]} />
                        <mesh geometry={nodes.CurtainPole_CurtainPole_0.geometry} material={materials.CurtainPole} position={[0, 1.1, 0.79]} rotation={[0, Math.PI / 2, 0]} scale={[0.02, 0.01, 0.61]} />
                        <mesh geometry={nodes.Curtains_Curtains_0.geometry} material={materials.Curtains} position={[0, 1.07, 0.27]} scale={[0.16, 0.37, 0.13]} />
                        <mesh geometry={nodes.Paintings_Paintings_0.geometry} material={materials.Paintings} position={[1.17, 0.17, 0.01]} scale={[0.07, 0.06, 0.13]} />
                        <mesh geometry={nodes.PictureFrame_PictureFrame_0.geometry} material={materials.PictureFrame} position={[-1.18, 0.06, 0.01]} scale={[0.52, 0.62, 0.93]} />
                        <mesh geometry={nodes.Picture_Picture_0.geometry} material={materials.Picture} position={[-1.17, 0.06, 0.01]} scale={[0.52, 0.62, 0.93]} />
                        <mesh geometry={nodes.Plant_Plant_0.geometry} material={materials.Plant} position={[0, 0.06, -0.18]} scale={[0.04, 0.03, 0.08]} />
                        <mesh geometry={nodes.Carpet_Carpet_0.geometry} material={materials.Carpet} position={[0, 0.06, -1.09]} scale={[0.89, 0.52, 0.17]} />
                        <mesh geometry={nodes.LightChrome_LightChrome_0.geometry} material={materials.LightChrome} position={[0, 0.06, 0.83]} scale={[0, 0, 0.01]} />
                        <mesh geometry={nodes.LightGlass_Lights_0.geometry} material={materials.Lights} position={[0, 0.06, 0.46]} scale={[0, 0, 0.01]} />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/scene.glb')
