/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Sololopenko (https://sketchfab.com/Sololopenko)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/furniture-set-4eb801eccae644ee9ded7a13f8d49d8a
title: Furniture set
*/

import { useGLTF } from '@react-three/drei'
import {Canvas} from "@react-three/fiber";

import { Environment, OrbitControls, PerspectiveCamera, Sky } from '@react-three/drei';
import { useFrame, useLoader } from '@react-three/fiber';
import React, {Suspense, useRef } from 'react';
import * as THREE from 'three';
import {gsap} from 'gsap';
import { useIsomorphicLayoutEffect } from 'usehooks-ts'
import {angleToRadians} from "../../utils/angle";
import Vase from "../Room/Vase";
import Chair from "../Chair";
import Sofa from "../Sofa";
import CoffeeTable from "../CoffeeTable";

function Model(props) {
    const { nodes, materials } = useGLTF('/models/furniture/scene.glb')
    return (
        <group {...props} dispose={null} position={[0, 0, 0]}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={2.4} >
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[-1.12, 0, -0.22]} rotation={[0, 0.62, 0]}>
                        <mesh geometry={nodes.Object_24.geometry} material={materials.furniture} />
                        <mesh geometry={nodes.Object_25.geometry} material={materials.monstera} />
                    </group>
                    <mesh geometry={nodes.Object_4.geometry} material={materials.furniture} position={[-0.68, 0, 0.44]} rotation={[-Math.PI, 1.09, -Math.PI]} scale={0.84} />
                    <mesh geometry={nodes.Object_6.geometry} material={materials.furniture} position={[0.43, 0, -0.9]} rotation={[0, -0.36, 0]} scale={0.84} />
                    <mesh geometry={nodes.Object_8.geometry} material={materials.furniture} position={[0.2, 0.39, -0.02]} rotation={[0, 1.02, 0]} />
                    <mesh geometry={nodes.Object_10.geometry} material={materials.furniture} position={[0.08, 0.39, 0.11]} rotation={[-Math.PI, -0.65, -Math.PI]} />
                    <mesh geometry={nodes.Object_12.geometry} material={materials.furniture} position={[0.2, 0.38, -0.02]} rotation={[0, 0.45, 0]} />
                    <mesh geometry={nodes.Object_14.geometry} material={materials.furniture} position={[0.08, 0.38, 0.11]} rotation={[-Math.PI, 1.48, -Math.PI]} />
                    <mesh geometry={nodes.Object_16.geometry} material={materials.furniture} position={[-0.52, 0, -0.76]} rotation={[0, 0.51, 0]} scale={0.84} />
                    <mesh geometry={nodes.Object_18.geometry} material={materials.furniture} position={[0.23, 0, 0.15]} rotation={[0, 0.03, 0]} />
                    <mesh geometry={nodes.Object_20.geometry} material={materials.furniture} position={[0.34, 0.39, 0.25]} rotation={[Math.PI, -1.14, Math.PI]} />
                    <mesh geometry={nodes.Object_22.geometry} material={materials.furniture} position={[0.27, 0.39, 0.25]} rotation={[0, 0.54, 0]} />
                </group>
            </group>
        </group>
    )
}

// useGLTF.preload('/scene.glb')



function Furniture(props) {

    const orbitControlsRef = useRef(null);

    useFrame((state) => {
        if(!!orbitControlsRef.current){
            const { x, y } = state.mouse;
            orbitControlsRef.current.setAzimuthalAngle(-x * angleToRadians(5));
            orbitControlsRef.current.setPolarAngle((y + 5.5) * angleToRadians(5));
            orbitControlsRef.current.update();
        }
    });

    const t1 = gsap.timeline();

    let ballRef = useRef(null);

    // useIsomorphicLayoutEffect(() => {
    //     let ctx = gsap.context(() => {
    //         t1.to(ballRef.current.position, {
    //             duration: 2,
    //             x: 1,
    //             ease: "power2.out",
    //
    //         })
    //             .from(ballRef.current.position, {
    //                 y: 2,
    //                 duration: 2,
    //                 ease: "bounce.out",
    //             },">");
    //     }, ballRef); // <- scopes all selector text to the root element
    //
    //     return () => ctx.revert();
    // }, );


    return (
        <>

            {/* Perspective Camera */}
            <PerspectiveCamera makeDefault position={[0, 2, 5]}/>

            <OrbitControls ref={orbitControlsRef} autoRotate enableZoom={false}
                // minPolarAngle={angleToRadians(60)}
                // maxPolarAngle={angleToRadians(80)}
            />

            {/* Ambient Light */}
            <ambientLight intensity={0.4} />
            <directionalLight
                castShadow
                position={[2.5, 8, 5]}
                intensity={1.5}
                shadow-mapSize-width={1024}
                shadow-mapSize-height={1024}
                shadow-camera-far={50}
                shadow-camera-left={-10}
                shadow-camera-right={10}
                shadow-camera-top={10}
                shadow-camera-bottom={-10}
            />
            <pointLight position={[-10, 0, -20]} color={'#fff'} intensity={2.5} />
            <pointLight position={[0, -10, 0]} intensity={1.5} />

            <Model castShadow/>

        </>
    );
}

export default Furniture;
